### ISSUE TITLE
JSON Object of Current Model State?

### ISSUE THREAD

**Issue by nicholaswyoung** [vdemedes/mongorito#10]
How would I access the current model state as a JSON object? (I'm using Joi to handle validation). Basically, I need something like this:

```javascript
* validate (next) {
   let schema = {
      title: joi.string()
   };
   
   let currentState = {
      title: this.get('title')
   };

   joi.validate(schema, object, {}, function (err) {
      if (err) throw err;
      yield next;
   });
}
```
Does this look correct?

**Comment by vdemedes** [comment]
`this.toJSON()` or `this.attributes` return the attributes of the model.

**Comment by nicholaswyoung** [comment]
Excellent. Thanks again!
