### ISSUE TITLE
how use getCollectionNames()

### ISSUE THREAD

**Issue by tonytcb** [vdemedes/mongorito#102]
Hi, how i can use the mongo command: "db.getCollectionNames()".

It's possible from Mongorito?

Thanks anyway

**Comment by vdemedes** [comment]
No, not possible at the moment. For now you can access native driver via undocumented property `Mongorito.db`.

**Comment by tonytcb** [comment]
@vdemedes Sorry, but i could not do this.

`
var mongorito = require('mongorito');
mongorito.db.getCollectionNames(function(res) {
    console.log(res);
});
`

It's right?

**Comment by tonytcb** [comment]
@vdemedes Solved.

`mongorito.db.listCollections().toArray(function(err, collections){`
`    console.log('/////////////////// listCollections');`
`    console.log(err);`
`    console.log(collections);`
`});`

Thanks again.
