### ISSUE TITLE
Sanitizing input via this.attributes

### ISSUE THREAD

**Issue by nicholaswyoung** [vdemedes/mongorito#11]
I just tried to assign ```this.attributes``` to a sanitized object (in a pre-save validation function), and get an error:

```
Cannot read property 'created_at' of undefined
```
Which, I assume, means I overrode something that I should've left alone. Is there a clean way to handle this at the model level, or should I do sanitization before it hits the model?

**Comment by vdemedes** [comment]
I would do validation/sanitization in a hook. In your case, there should be something wrong with your code.
