### ISSUE TITLE
Hooks running more than once

### ISSUE THREAD

**Issue by brielov** [vdemedes/mongorito#113]
I have a user model that runs three hooks before save: validateEmail, validatePassword, encryptPassword.

In the test file, I do:

`const user = new User({ email: 'user@example.com', password: '' })`
`yield user.save() // assert throws error`
`user.set('password', 'Example123')`
`yield user.save() // test should pass`

But then the hooks run like this:
Validate email
Validate password
Encrypt password
Validate email
Validate password

So when the encrypt password hook is called, a hashed version of the password is set using

`user.set('password', yield bcrypt.hash(this.get('password'), 10))`

the validate password hook fails because password is too long.

![screen shot 2016-05-02 at 10 34 34](https://cloud.githubusercontent.com/assets/14098533/14955626/9d10d3a8-1051-11e6-8aac-d349dfd2bc44.png)
![screen shot 2016-05-02 at 10 34 58](https://cloud.githubusercontent.com/assets/14098533/14955627/9d4a8af8-1051-11e6-9a3e-33d12fdde824.png)
![screen shot 2016-05-02 at 10 35 11](https://cloud.githubusercontent.com/assets/14098533/14955628/9d4aa38a-1051-11e6-9ac1-caa6d80718da.png)
![screen shot 2016-05-02 at 15 04 08](https://cloud.githubusercontent.com/assets/14098533/14962842/34d20cf0-1077-11e6-8fa1-7e9644286717.png)

**Comment by vdemedes** [comment]
> But then the hooks run like this:
Validate email
Validate password
Encrypt password
Validate email
Validate password

It looks correct. What is the issue specifically?

**Comment by brielov** [comment]
It is duplicating hooks... It should run Validate Email => Validate Password => Encrypt Password. But instead it is running Validate Email and Validate Password after Encrypt Password. Encrypt Password should be the last hook to run

**Comment by vdemedes** [comment]
Could you do a PR with a failing test?

**Comment by zaaack** [comment]
https://github.com/vdemedes/mongorito/blob/master/lib/mongorito.js#L521

I just find out the `_getHooks()` method might cause a leak, would it be related?

**Comment by zaaack** [comment]
@vdemedes  And there are a lot of test failures in the main branch, is that OK?

**Comment by zaaack** [comment]
Looks like mongodb client

**Comment by vdemedes** [comment]
Should be fixed now thanks to @zaaack. Published on npm as `2.2.0`.
