### ISSUE TITLE
authentication in connection

### ISSUE THREAD

**Issue by ulpian** [vdemedes/mongorito#124]
What is the best way to authenticate with a mongo database with mongorito, i.e authentication with a user that exists on the standard `admin` database;

Is there a way to do this?

```
db.authenticate('user','password','--authenticationDatabase admin')
```

Which can be done with the native mongodb driver. [https://mongodb.github.io/node-mongodb-native/api-generated/db.html#authenticate](https://mongodb.github.io/node-mongodb-native/api-generated/db.html#authenticate) - possibly expose this command?

*update;

used an old version of mongodb driver documentation; meant the `authSource` key in [http://mongodb.github.io/node-mongodb-native/2.1/api/Db.html#event:authenticated](http://mongodb.github.io/node-mongodb-native/2.1/api/Db.html#event:authenticated)

**Comment by vdemedes** [comment]
Your connection URL should be like:

```
mongodb://username:password@host:port/database
```
