### ISSUE TITLE
Expose ObjectID from mongoskin

### ISSUE THREAD

**Issue by floatdrop** [vdemedes/mongorito#13]
Is there any chance to expose MongoDB objects from mongorito?

In utils you get them from mongoskin: https://github.com/vdemedes/mongorito/blob/master/lib/util.js#L5 but in my code it will be look like:

```js
var ObjectID = require('mongorito/node_modules/monk/node_modules/mongoskin').ObjectID;
```

This is far beyond good path for require - can it be like this (ideal):

```js
var ObjectID = require('mongorito').ObjectID;
```

P.s. Thanks for awesome module :dog:

**Comment by vdemedes** [comment]
With latest mongorito on npm now (0.6.5) you can get ObjectID, just like you showed before:

```javascript
var ObjectID = require('mongorito').ObjectID;
```

P.S. Thank you, glad you find it useful!

**Comment by floatdrop** [comment]
@vdemedes thanks! Any plans to add other stuff to exports (like mongoskin does - https://github.com/kissjs/node-mongoskin/blob/master/lib/index.js#L16-L21)?

**Comment by vdemedes** [comment]
Good idea, I will check out what it exports and if it will not have any conflicts, I'll implement it.

**Comment by vdemedes** [comment]
@floatdrop mongorito@0.6.8 now exports everything from mongodb package.

**Comment by floatdrop** [comment]
@vdemedes sweet. thanks! :star:
