### ISSUE TITLE
Plugins?

### ISSUE THREAD

**Issue by nicholaswyoung** [vdemedes/mongorito#14]
Do you have tips on implementing Mongoose-style plugins for Mongorito? I would love to port several of our plugins that add methods, statics, and other query helpers in a DRY fashion.

**Comment by floatdrop** [comment]
@nicholaswyoung why don't you just extend `Model` to `MyModel` with additional methods and stuff and then extend `MyModel` in your application?

**Comment by nicholaswyoung** [comment]
@floatdrop Good point. I don't know why I didn't think of that. I'll give it a shot and report back.

**Comment by vdemedes** [comment]
Thanks for suggestion, I will consider adding this functionality in future releases. For now, you can just extend `Model.prototype` for instance methods and `Model` for static methods.

**Comment by nicholaswyoung** [comment]
@vdemedes Thanks! For now, extending the model should do fine.

**Comment by vdemedes** [comment]
Closed due to the existing solution.
