### ISSUE TITLE
Does Mongorito support SSL in the connection string

### ISSUE THREAD

**Issue by nergmada** [vdemedes/mongorito#140]
I'm interested in connecting to a separately hosted mongo instance for my application. Does Mongorito support SSL on the connection string?

**Comment by vdemedes** [comment]
Yes, I was using Mongorito with SSL endpoints successfully (I was using compose.io). I had to append `?ssl=true` to connection string and supply custom SSL certificate:

```js
const certificate = fs.readFileSync(certificatePath);

mongorito.connect(url, {
   mongos: {
      ssl: true,
      sslValidate: true,
      sslCA: [certificate]
   }
});
```

**Comment by duartealexf** [comment]
For anyone who also run into this, all the options are available at:
http://mongodb.github.io/node-mongodb-native/2.2/tutorials/connect/ssl/
