### ISSUE TITLE
Save function was not able to save my data

### ISSUE THREAD

**Issue by rack021** [vdemedes/mongorito#141]
const DB = require('mongorito');
const Model = DB.Model;
const run = require('./util/run');

class User extends Model {
  constructor() {
    super();
    this.name = String;
  }
}

DB.connect("localhost:27017/settrip_db").then(function (db) {
  run(function* () {
    var user1 = new User({
      'name': 'Rac'
    });
    yield user1.save();
    console.log(user1.get());
    yield DB.disconnect();
  });

});

// result

{ created_at: 2016-09-30T09:25:46.841Z,                                                                                                                                 
  updated_at: 2016-09-30T09:25:46.841Z,                                                                                                                                 
  _id: 57ee2f9a1101e708c81b8cb7 } 

I don't know why, but it was not able to save my data in db, can explain what i am doing wrong?

**Comment by vdemedes** [comment]
```js
class User extends Model {
constructor() {
super();
this.name = String;
}
}
```

Mongorito does not have schemas, try removing `this.name = String`.

**Comment by rack021** [comment]
Oh, Gosh, how did I miss that, thank you very much, and thank you for such great ORM

**Comment by vdemedes** [comment]
Glad you like it, v3 is coming soon ;)

**Comment by rack021** [comment]
I am waiting for it, I wish it can be released today itself so, i can incorporate in my new project from initial phase itself and we don't need to update it later. :D
