### ISSUE TITLE
Query operator OR

### ISSUE THREAD

**Issue by Zhigalov** [vdemedes/mongorito#15]
I need to make a request like `{ $or: [{ a:1 },  { b:2 }] }`

If I use method
``` JavaScript
MyModel.or([{ a:1 }, { b:2 }]).find()
```
than I get a request `{"[object Object],[object Object]":{}}` because in [here] (https://github.com/vdemedes/mongorito/blob/master/lib/query.js#L201-L203) key-value pair is required.

If I use 
``` JavaScript
MyModel.find({ $or: { a:1 },  { b:2 }})
```
 then my request transforms to `{"$or":{"$elemMatch":[{"a":1},{"b":2}]}` [because of](https://github.com/vdemedes/mongorito/blob/master/lib/query.js#L47).

So the question is, what is a correct way to make a request like `{ $or: [{ a:1 }, { b:2 }] }`?

**Comment by floatdrop** [comment]
@vdemedes is there any chance to get [mquery](https://github.com/aheckmann/mquery) adopted as querybuilder?

**Comment by vdemedes** [comment]
@floatdrop I don't think so, not yet.

**Comment by vdemedes** [comment]
@Zhigalov thank you for PR, commented there.

**Comment by vdemedes** [comment]
mongorito@0.6.9 now can do this:

```javascript
Post.or({ a: 1 }, { b: 2 });

// OR

Post.or([{ a: 1 }, { b: 2 }]);
```
