### ISSUE TITLE
It is possible to find with $and logic operator

### ISSUE THREAD

**Issue by pipo02mix** [vdemedes/mongorito#18]
I am trying to find a document in a mongodb collection from two properties. Example:

```js
class Session extends Model {
  getCollection() { 
    return 'sessions';
  }
}

var sessions = yield Session.where(
   { status: 'active' , owner: 'mine'} //by default is applying 'or'
  ).find();
```

I have tried doing (mongo driver style)
```js
var sessions = yield Session.where(
   { $and: [
      { status: 'active' },
      { owner: 'mine' }
  ]}).find();
```
but I think it is not supported.
Is there a way to achieve with this library?

Thanks

**Comment by vdemedes** [comment]
```javascript
var sessions = yield Session.and({ status: 'active' }, { owner: 'mine' }).find();
```

**Tip**: with latest Mongorito, you don't need to specify collection name any more, so you can remove `get collection()`.

**Comment by pipo02mix** [comment]
Nice and clear!
