### ISSUE TITLE
how to set collection with "class" keyword

### ISSUE THREAD

**Issue by butaixianran** [vdemedes/mongorito#20]
This is not an issue, I just need a little help here.

In the "Getting Started" page, it shows a way to define a Post with "class" keyword:
class Post extends Model {}

Then, how should I set the collection?
I tried something like this:

  class Post extends Model {
    constructor() {
      super(); 
      this.collection = 'posts';
    }

but doesn't work. I don't want to use:
  var Post = Model.extend({collection: 'posts'});
I wanna use the "class" keyword. 

Then how should I set the collection? thanks.

**Comment by vdemedes** [comment]
In the following case:

```javascript
class Post extends Model {}
```

collection name would be automatically set to "posts". If you need custom collection name:

```javascript
class Post extends Model {
  get collection () { return 'my_posts_collection'; }
}
```

**Comment by butaixianran** [comment]
thanks:)
