### ISSUE TITLE
Short id for "_id" doesn't work with .save()

### ISSUE THREAD

**Issue by butaixianran** [vdemedes/mongorito#22]
I created my own short id like {_id: "mJTXnQhs", name: "kevin"}, but when trying to .save(), it throw this err:
Argument passed in must be a single String of 12 bytes or a string of 24 hex characters

It's ok if I insert this doc from mongo's shell like this: db.myCollection.insert({_id: "mJTXnQhs", name: "kevin"}).

Then how should I use my own short id for "_id" with mongorito? 
Thanks.

btw, mongorito is amazing, it helps a lot.

**Comment by vdemedes** [comment]
_id field is ObjectID - http://docs.mongodb.org/manual/reference/object-id/. I recommend you to read this article, it forces a specific format, so you can't assign something custom to it, because Mongorito converts value of _id to ObjectID:

```javascript
ObjectID(_id)
```

so it throws an exception, if _id does not conform to ObjectID format.

P.S. Thank you, glad you like it.

**Comment by butaixianran** [comment]
hi, I read and checked a lot of articles about ObjectId, and there are many people like to use a shortId instead.

It's fine that Mongorito want to convert id into ObjectId as default, but could you at least offer a way to override the converting function? Then we can use a shortId if we want.

For now, I try to do something like this:
collection.id = function (str) { return str; };

But it gives an error says:
Cannot assign to read only property 'id'

Thanks

**Comment by vdemedes** [comment]
I would suggest using "short_id" (for example) field for your short ids and create an index on that field. And I recommend you to not assign something custom to _id, since it is a default.

**Comment by butaixianran** [comment]
That's what I've done for now. The problem is, when updating, Mongorito is update by _id, not my short_id.

So I have to query "_id" by my short_id first, then update doc with "_id". Which means I have to access mongo db twice.

If I can update my doc with short_id, then it will be ok to leave _id as default.
