### ISSUE TITLE
Mongorito.close() is async, but not yield friendly.

### ISSUE THREAD

**Issue by butaixianran** [vdemedes/mongorito#23]
When reconnect mongo After Mongorito.close(), and do some save/query, it will throw an err that "connection is closed by Application."

which is casued by Mongorito.close() is async, but not yield friendly.

Here is an example:

```
co(function(){
    Mongorito.connect(url);
    //get data from mongo
    Mongorito.close();   //<- it's async, but not yield friendly.
}).then(function(doc){
    // ---->connection is still open.
    Mongorito.connect(url);
    // ---->connection is just closed.
    //update doc and save to mongo. <- Get an err caused by "Connection is closed"
    Mongorito.close();
})
```

Then how could I do Mongorito.close() with yield? thanks.

**Comment by vdemedes** [comment]
Thanks for reporting, will fix.

**Comment by butaixianran** [comment]
I figure out that:
Not like C#/Java people open and close db connection with every query, Nodejs people just never close a db connection.

If .close() is barely used, then this is not an issue anymore, it's just a style.

**Comment by vdemedes** [comment]
It is not always true, so this issue has to be solved. 

Regards,
Vadim.

**Comment by vdemedes** [comment]
Fixed in latest master branch.

**Comment by akanieski** [comment]
@butaixianran Why wouldn't you want to close a db connection with node?
