### ISSUE TITLE
TypeError: Cannot read property 'is' of undefined

### ISSUE THREAD

**Issue by maxfrigge** [vdemedes/mongorito#27]
I'm running the latest version (0.6.13 ) with iojs 1.5.1 using --es_staging --use_strict.

Here is the stack trace:

    |TypeError: Cannot read property 'is' of undefined
    |     at /usr/src/app/node_modules/mongorito/node_modules/is_js/is.js:29:26
    |     at root (/usr/src/app/node_modules/mongorito/node_modules/is_js/is.js:18:26)
    |     at Object.<anonymous> (/usr/src/app/node_modules/mongorito/node_modules/is_js/is.js:23:2)
    |     at Module._compile (module.js:444:26)
    |     at Object.Module._extensions..js (module.js:462:10)
    |     at Module.load (module.js:339:32)
    |     at Function.Module._load (module.js:294:12)
    |     at Module.require (module.js:349:17)
    |     at require (module.js:368:17)
    |     at Object.<anonymous> (/usr/src/app/node_modules/mongorito/build/mongorito.js:22:10)
    |     at Module._compile (module.js:444:26)
    |     at Object.Module._extensions..js (module.js:462:10)
    |     at Module.load (module.js:339:32)
    |     at Function.Module._load (module.js:294:12)
    |     at Module.require (module.js:349:17)
    |     at require (module.js:368:17)

**Comment by vdemedes** [comment]
Thanks for reporting, the issue comes from [is.js](http://arasatasaygin.github.io/is.js/) library, in the source code it says it does not support strict environments.

**Comment by vdemedes** [comment]
Submitted a PR to this library to fix this.

**Comment by maxfrigge** [comment]
Thanks! I will use 0.6.11 until then.

**Comment by vdemedes** [comment]
Yep, it's safe to use this one, no major changes between 0.6.12.

**Comment by arasatasaygin** [comment]
Merged the fix of @vdemedes 
Thanks
