### ISSUE TITLE
Incorrect syntax in middleware guides

### ISSUE THREAD

**Issue by maxfrigge** [vdemedes/mongorito#28]
I found this one browsing through the guides.

It currently says

    class Post extends Model {
        configure () {
            this.before('create', 'checkIfExists');
        }

        * checkIfExists: function (next) {
            // checking if post with the
            // same title exists in database

            yield next;
        }
    }

But it should actually be

    class Post extends Model {
        configure () {
            this.before('create', 'checkIfExists');
        }

        * checkIfExists (next) {
            // checking if post with the
            // same title exists in database

            yield next;
        }
    }

**Comment by vdemedes** [comment]
Thanks for spotting this!
