### ISSUE TITLE
Upgrade monk to 1.0.0

### ISSUE THREAD

**Issue by maxfrigge** [vdemedes/mongorito#29]
Would you mind upgrading monk to 1.0.0?

It appears that it would fix this annoying little thing when using iojs:

    js-bson: Failed to load c++ bson extension, using pure JS version

**Comment by vdemedes** [comment]
This issue is more likely caused by Node.js version switching. If you switch to another version, you need to rebuild dependencies. But I'll upgrade anyway, thank you.
