### ISSUE TITLE
Error occured while fetch all records

### ISSUE THREAD

**Issue by asci** [vdemedes/mongorito#32]
on start I get this error:
```
[Error: Module did not self-register.]
js-bson: Failed to load c++ bson extension, using pure JS version
```

and when I try to `yield SomeModel.all();`
this error throws:

```
TypeError: Cannot read property 'find' of undefined
      at Query.find (/Users/artem/Projects/elastic/metagen/node_modules/mongorito/lib/query.js:127:37)
      at GeneratorFunctionPrototype.next (native)
```

My model looks like

```
var Mongorito = require('mongorito');
var Model = Mongorito.Model;
Mongorito.connect('mongodb://localhost:27017/mydb');

var Api = Model.extend({
    collection: function () {
        return 'apis';
    }
});

module.exports = Api;
```

I'm using Koajs and iojs

**Comment by vdemedes** [comment]
Does this error occur when using `.find()` or any other query methods?

**Comment by vdemedes** [comment]
It is also weird that you are getting this error, because I have this covered in tests and tests run ok (https://github.com/vdemedes/mongorito/blob/master/test/mongorito.test.js#L258).

**Comment by asci** [comment]
Yes, it occurs with find. Maybe it because in NPM mongorito v1.0.0 ?

**Comment by vdemedes** [comment]
Could you paste more of your code, for me to reproduce this?

**Comment by vdemedes** [comment]
Run `npm rebuild` to fix the following error:

```
[Error: Module did not self-register.]
js-bson: Failed to load c++ bson extension, using pure JS version
```

**Comment by vdemedes** [comment]
Mongorito depends on some modules, that need to be compiled. When you switch Node.js/io.js version without `npm rebuild`, this error will appear.

**Comment by vdemedes** [comment]
Error reproduced, figuring out how to fix it, thanks for reporting!

**Comment by vdemedes** [comment]
Found a cause. It is because of `.extend()` way of defining your models. If you'll use ES6 classes, it should be fine. Meanwhile, I am trying to fix `.extend()` now.

**Comment by vdemedes** [comment]
Fixed and available on npm as `mongorito@1.1.1`.

**Comment by asci** [comment]
Thanks, that was really fast:)
btw, it is not my busy, but removing this way of defining model till even iojs doesn't have it without flag — not good)

**Comment by vdemedes** [comment]
Who said I removed `.extend()`? :D It's still there, but rewritten and working as expected! You can go back to defining models with `.extend()` now, but I strongly encourage you to switch to ES6 classes.
