### ISSUE TITLE
save returning without actually saving the document

### ISSUE THREAD

**Issue by suparngp** [vdemedes/mongorito#36]
Firstly, I am not using co or any other library like that. 

<pre>
<code>
function* p() {
    Mongorito.connect('ipaddress/blog');
    var post = new Post({
        title: 'Node.js with --harmony rocks!',
        body: 'Long post body',
        author: {
            name: 'John Doe'
        }
    });
    yield post.save();
}
var x = p();
console.log(x.next());
</code>
</pre>

The above code should have worked IMO because p() will not yield until the document has been saved.
However, post.save() yields immediately with the output <code>{ value: {}, done: false }</code>.

The following code does save the document but <b>yields a function</b>

<pre>
<code>
yield* post.create(); //replaced yield.post.save()
</code>
</pre>

Output:
<pre>
<code>
{ value: [Function], done: false }
</code>
</pre>

I can see that the new document has been saved in the MongoDB. 
Can some one please help?

**Comment by vdemedes** [comment]
You should use [co](https://github.com/tj/co) and everything will work as expected.
