### ISSUE TITLE
Cannot perform text search in documents.

### ISSUE THREAD

**Issue by adrianca** [vdemedes/mongorito#37]
First and foremost, thank you for such great work. I really like your project and the idea of hooks is awesome. Please take a minute to review my issues, I tried the guides and there's no example for this situation.

I currently have a collection with a text index. Using the mongo console, I am able to search my documents like so:

`db.cities.find({
    '$text': {
      '$search': 'San Francisco'
    }
  }`

I have tried this using Mongorito: 
`let cities = yield City.where({'$text': {$search: 'San Francisco'}}).find();`

and also the find version of it:
`let cities = yield City.find({'$text': {$search: 'San Francisco'}})`

This search never returns any results though. I suspect is due to the fact that it is searching in the existing model properties, and `$text` is a reserved mongo property. How could I achieve this?

Also, another common operation when dealing with text search is to sort on the `$textScore` meta property. For instance:

`db.cities.find({
    '$text': {
      '$search': 'San Francisco'
    }
  }, {'score': {'$meta': 'textScore'}})
  .sort({'score': {'$meta': 'textScore'}})
`

This code is finding the city with the text *San Francisco* in the indexed text property, then projecting the `textScore` meta property, then sorting using that score. How would you be able to achieve this using Mongorito?

Thank you.

**Comment by vdemedes** [comment]
Hello, thank you for the kind words, it means a lot to me!

Sorry for much delayed response, I've been very busy lately. This certainly looks like a must-have feature for Mongorito, so let me investigate a bit about what I can do and get back to you with a solution.

Thank you for suggestion!

**Comment by maxfrigge** [comment]
One thing that came to my mind when I read this is to add a getter `Model.raw` which gives direct access to the mongo collection (e. g. db.cities). This way you would get the full power of mongo without adding too many complex features to the ORM. 

`let cities = City.raw.find({ '$text': { '$search': 'San Francisco' } }, {'score': {'$meta': 'textScore'}}) .sort({'score': {'$meta': 'textScore'}})`

I have seen this in other lightweight ORMs before and always found it to be very handy.

**Comment by vdemedes** [comment]
@maxfrigge possible solution, but it would prevent me to migrate underlying libraries to talk to mongodb. I had an idea to migrate from monk to [mongodb-core](https://www.npmjs.com/package/mongodb-core) to increase performance. But with this solution, I wouldn't be able to do that without breaking people's apps.

**Comment by maxfrigge** [comment]
@vdemedes good point. In that case it's probably best to settle for a mongo lib first before adding any access to the underlying system (if at all). 

So what would be your take on using a feature that's not supported by mongorito?
Use e.g. monk alongside with mongorito?

**Comment by vdemedes** [comment]
@maxfrigge That is, of course, a solution but a very bad one. I'll see what I can do. Unfortunately, I am very busy this and the following week, so I can't guarantee a quick fix.

**Comment by vdemedes** [comment]
@adrianca @maxfrigge Pushed `mongorito@1.3.1`, which fixes current issue. Example:

```javascript
let posts = yield* Post.search('San Francisco').sort('score', {
  '$meta': 'textScore'
}).include('score', {
  '$meta': 'textScore'
}).find();
```

Thank you for submitting the issue and participating!
