### ISSUE TITLE
Query problem ($elemMatch misuse)

### ISSUE THREAD

**Issue by Volox** [vdemedes/mongorito#38]
Hello,
I have some problems with the query creation and i think the problems are related to the use of `$elemMatch` (here [src/query.js](https://github.com/vdemedes/mongorito/blob/93f32e3222473dfd29aa283b798f0afcc05034ed/src/query.js#L58)).

My code is basically like this:
```js
let query = {
  "date": {
      "$gte": "2015-05-05T00:00:00.000Z", // Not the string, the Date object
      "$lte": "2015-05-06T23:59:59.999Z" // Not the string, the Date object
    }
};

let result = yield* query.find( query );
```

But if i enable the `DEBUG` i see the generated query is:
```
monk:queries posts find {"date":{"$elemMatch":{"$gte":"2015-05-05T00:00:00.000Z","$lte":"2015-05-06T23:59:59.999Z"}}}
```

And i get no results while using the mongo console my query works.

The problem is related to the fact that `$elemMatch` works on array fields (see [here](http://docs.mongodb.org/manual/reference/operator/query/elemMatch/))
> The $elemMatch operator matches documents that contain an array field with at least one element that matches all the specified query criteria.

**Comment by vdemedes** [comment]
Hello,

Yes, you are right, the problem is related to `.where()` implementation and how it treats objects. As a solution, I suggest the following:

```javascript
let results = yield* Model.gte(startDate).lte(endDate).find();
```

Let me know how that works ;)

**Comment by vdemedes** [comment]
Pushed a change, which introduces a `matches()` method for `$elemMatch` usage and allow any object for `where()`, so any MongoDB operators can be used, in case they are not supported by Mongorito.

Thank you for posting this issue!
