### ISSUE TITLE
CircleCI build error

### ISSUE THREAD

**Issue by amit777** [vdemedes/mongorito#46]
Hi, I've run the test suite from my local machine and everything looks like it's passing.  However, the badge for CirculeCI is showing a failure.

**Comment by vdemedes** [comment]
Hi, yes, I am aware of this issue. It happened after I added full text search capabilities to Mongorito and ability to include/exclude fields from query results. Unfortunately, don't have time at the moment to investigate why tests are failing on CircleCI.

**Comment by vdemedes** [comment]
The issue was caused by old version of mongodb on circle/travis. Now I am installing mongodb manually, so the issue is gone.
