### ISSUE TITLE
Can't change default mongodb options in mongorito.connect?

### ISSUE THREAD

**Issue by fishmacs** [vdemedes/mongorito#48]
seems mongorito.connect only accepts url arguments, how can I change some options like poolSize, socketOptions,...?

**Comment by vdemedes** [comment]
Added ability to set options, usage:

```javascript
mongorito.connect('serverA', 'serverB', { poolSize: 5 });
mongorito.connect(['serverA', 'serverB'], { poolSize: 5 });
```

Available on npm as `mongorito@1.3.5`.
