### ISSUE TITLE
Equivalent of $push ?

### ISSUE THREAD

**Issue by HereThereBeMonsters** [vdemedes/mongorito#51]
Hi,

I am quite new to node AND mongo, please be patient :)

I am currently in the process of rewriting a webapp's persistence using mongorito. So far I like it quite a lot.

But I need to do things like add comments to an issue, or add followers. These are represented in my schema as arrays of ids or arrays of objects inside the main document.

It used to be implemented using the native mongo `$push` keywords, like this: 

    db.discussion.update(
        { 'discussion_id': discussion_id },
        { '$push': { 'comments': {
            'posted': datetime.utcnow(),
            'author': author_info,
            'text': comment_text } } } );

Using Mongorito, I could not find an equivalent to this construct. The workaround is to load the whole parent (`discussion` in this example), add the comment or follower, and finally save the whole object again. This is not optimal. 2 DB hits instead of one, and potentially loading a big object just to add a single id in an array.

What would you recommend instead ? Is there support for this kind of operations built into Mongorito ?

**Comment by vdemedes** [comment]
Hello,

There's no support currently for `$push`. I'd recommend just storing documents in separate collections, rather than `$push`ing to one document.

**Comment by HereThereBeMonsters** [comment]
Hello,

Isn't one of the main selling points of MongoDB the ability to store multiple related objects in a single documents, and then retrieve them in a single, really fast operation and without joins ? 

The official mongo doc describes embedding comments as a sub-tree of a topic as one of the options for that particular use case : http://docs.mongodb.org/ecosystem/use-cases/storing-comments/

That said, I understand that the $push, partial $update, $slice etc. operators are not a very good match for the active record pattern implemented by mongorito, and I guess I could just use the Mongo or Monk API directly if I really need them.

**Comment by vdemedes** [comment]
Hi, yes, you are right about that and I agree. But I wanted to follow (as you said) active record pattern to make things as easy and understandable as possible, so that's why the support for $push is not there. Anyway, I will think about it, thank you for the suggestion!
