### ISSUE TITLE
Mongodb 3.x query format support

### ISSUE THREAD

**Issue by corporatepiyush** [vdemedes/mongorito#52]
Does Mongorito support all query expression as of MongoDB 3.x native driver ?
e.g.  db.<collection>.aggregate
 If yes can we update it to doc ?

**Comment by vdemedes** [comment]
Currently, it does not. I am planning to migrate off monk and switch to native driver instead. Right now it is mongorito -> monk -> mongoskin -> native mongo driver. However, it might not happen in the very near future, so stay tuned ;)

**Comment by paullryan** [comment]
@vdemedes pull #59 is a step in this direction moves to mongorito -> native mongo driver. I did not however change any query syntax stuff yet.
