### ISSUE TITLE
Pre Query middleware?

### ISSUE THREAD

**Issue by yulric** [vdemedes/mongorito#53]
Hi there,
I just started using this library and wanted to know if there's a way to execute a function before a query is sent to the database? My use case is that the data in the database is encrypted and I need to encrypt the query object before sending it to the database.

Thanks.

**Comment by vdemedes** [comment]
Hello,

Unfortunately, there's no way currently to have pre-query middleware.

Thanks for using mongorito!

**Comment by yulric** [comment]
No problem, love the library. Do you think there is a possibility of this feature being implemented in the future?

**Comment by vdemedes** [comment]
Can't say for sure. Glad you like it!
