### ISSUE TITLE
Co wrapper

### ISSUE THREAD

**Issue by be-codified** [vdemedes/mongorito#55]
"In addition to all that, all code that contains generators and yield statements needs to be wrapped into co or similar tools, that handle generators. This may be confusing at first, but in practice, it is very simple. Read co’s Readme.md to understand how it works better."

Can I ask for a simple sample?

**Comment by vdemedes** [comment]
Sure:

```js
const co = require('co');

co(function * () {
  let users = yield User.find();
});
```

**Comment by crapthings** [comment]
should i always use a co wrapper or babel generator is okay too ?

**Comment by vdemedes** [comment]
What is "babel generator"?

**Comment by crapthings** [comment]
i can make it work

looks great~

https://github.com/crapthings/inventor-server/blob/master/api/v1/posts.js#L9
