### ISSUE TITLE
Directly require mongoskin instead from monk's modules

### ISSUE THREAD

**Issue by maxfrigge** [vdemedes/mongorito#56]
I have seen that you require mongoskin doing `require('monk/node_modules/mongoskin')`.

After upgrading to node 4.1.1 and npm 3.3.5 this doesn't seem to work anymore, because in my case monk is now installed in my node_modules next to mongorito and thus `monk/node_modules/mongoskin` doesn't exist inside mongorito's node_modules. 

Couldn't you just `require('mongoskin')`?

**Comment by maxfrigge** [comment]
Thanks!

**Comment by vdemedes** [comment]
No, thank you! Good catch. Will publish in a few minutes to npm ;)

**Comment by maxfrigge** [comment]
:+1:  Sweet

**Comment by vdemedes** [comment]
Published on npm as `mongorito@1.3.6`.

**Comment by maxfrigge** [comment]
And it's working again :)

**Comment by vdemedes** [comment]
![](http://i.giphy.com/9e2q5dHXqavT2.gif)
