### ISSUE TITLE
Specifying an index

### ISSUE THREAD

**Issue by davidlawson** [vdemedes/mongorito#58]
I'm wondering what the best way is to specify an index for a Mongorito model.

Does something like this look right?

```js
class ModelName extends Model
{
  configure()
  {
    co(function*() {
      yield ModelName.index('fieldName');
    });
  }
}
```

**Comment by vdemedes** [comment]
`configure()` is executed every time you create a new instance of a model, so I do not recommend it. Just find a place, where you do it once, on startup.
