### ISSUE TITLE
Id's in findbyid are required to be wrapped in ObjectID

### ISSUE THREAD

**Issue by paullryan** [vdemedes/mongorito#60]
This can be an issue when trying to use requests from other systems which will have the ObjectID as just a string. Currently requires the user to include a library (e.g. full mongodb) directly to convert the string to an object Id.

Could be fixed by changing findById to:
```js
  /**
   * Find a document by ID
   *
   * @param {ObjectID|String} id - document id
   * @api public
   */

  static findById (id) {
    if(typeof id === 'string') {
      id = mongodb.ObjectID(id);
    }
    return this.findOne({ _id: id });
  }
```

and adding the test
```js
      it ('find one document by Id string', function * () {
        let data = postFixture();
        let post = new Post(data);
        yield* post.save();

        let posts = yield* Post.all();
        posts.length.should.equal(1);

        let createdPost = yield* Post.findById(post.get('_id').toString());
        createdPost.get('_id').toString().should.equal(post.get('_id').toString());
      });
```

Thus alleviating the need for another library inclusion. 

Could also be handled by a static helper on Model or Mongorito to make a string into an id.

**Comment by vdemedes** [comment]
Good suggestion.

**Comment by Globik** [comment]
Я чо-то вкурить не могу, почему у тебя в модуле так много зависимостей? Co-monk  к чему? Вы знаете, что ко-монк ни разу не обновляем с той поры вместе с монком? Монк тянет за собой устаревший монгоскин. К тому же у монк промисы не родные, а тянутся из кью-библиотеки. Ох и дурдом, я офигеваю. Нода 4.0 уже!! Проснись и пой!

**Comment by ulpian** [comment]
:+1:  this should probably be added on field that require *_id*;

```
.where('_id', 123...)
or
.find({ _id: 123... })
```

Surely that should cast to ObjectID straight away.
