### ISSUE TITLE
Timestamps (created_at, updated_at)

### ISSUE THREAD

**Issue by sidhuko** [vdemedes/mongorito#61]
It seems illogical to have a created_at and updated_at set on the before create hook. You don't know what async functions are being run and a JSON Schema validation will have to include these fields when they are system set in most APIs.

Also, not being able to turn them on/off and set the field names is restricting. Some people prefer camelCase over snake_case.
  
```
class User extends Mongorito.Model {

  configure () {
    this.before("create", "validate");
  }

  * validate(next) {
       console.log(this.get()) 
  }
}

```

**Comment by vdemedes** [comment]
`created_at` is assigned only on `before:create`, `updated_at` is updated on `before:save`.

But timestamps should be configurable, that's a fair point.

P.S. Try to use a more helpful title for issues in the future.

**Comment by sidhuko** [comment]
Sorry, there were a couple issues and I've a lot on, didn't want to not contribute my ideas but I've hacked it for now until I can come back to help. Great library by the way!

My point was created_at and updated_at are both set in the this.before("create", "fn) on this [line](https://github.com/vdemedes/mongorito/blob/master/lib/mongorito.js#L574). I think it would be logical to have them just before the entry is created on mongo rather than when the object is created in JavaScript. What do you think?

**Comment by vdemedes** [comment]
Oh I see what you mean now. Yeah, I think moving them few lines below won't hurt anyone.

**Comment by sidhuko** [comment]
Also, I think using a pattern of prefixing with an underscore to say their immutable would be good. I'm making these changes on a fork but when I've finished my project I'll tidy and PR.

**Comment by vdemedes** [comment]
> Also, I think using a pattern of prefixing with an underscore to say their immutable would be good

I wouldn't want such tricks in Mongorito.

**Comment by sidhuko** [comment]
Well if you're going to override them after hooks then save then you should document they aren't editable in some convention...

**Comment by vdemedes** [comment]
Wanted to implement this, but realized before and after hooks will have different input attributes, if I will set timestamps right before saving to the database.

To illustrate:

```js
runBeforeHooks(); // no created_at, updated_at
setTimestamps();
save();
runAfterHooks(); // timestamps are present
```

So, I think I will just make `created_at` and `updated_at` timestamp names configurable.

**Comment by sidhuko** [comment]
Well you've not created or updated the mongo transaction so that's understandable to a user. It's less understandable the object is showing created before being stored when this is a mongo ORM. Think I might fork instead of contributing as really have problems with your logic

**Comment by vdemedes** [comment]
Feel free to do so

**Comment by sidhuko** [comment]
Well this project seems dead really. No real community just offers es6 features so I'll likely see if I can contribute what I learn to mongoose. Can't run this in Babel either
