### ISSUE TITLE
Can't get it to work with Node.js v4.2.2

### ISSUE THREAD

**Issue by fmvilas** [vdemedes/mongorito#67]
Hi, thanks for the awesome work.

I'm trying out the examples you have in README and guides but can't get it to work. Using ```node --harmony app.js``` i get ```SyntaxError: Unexpected identifier``` on line ```yield Mongorito.connect('localhost/iris');```:

```
yield Mongorito.connect('localhost/iris');
      ^^^^^^^^^

SyntaxError: Unexpected identifier
```

I've tried also with --use_strict and --es_staging with no success.

Rings any bell?

**Comment by vdemedes** [comment]
Hey and glad you like Mongorito!

With Node.js v4.x you don't need any more flags like `--harmony` or `--es_staging`. Generators are enabled by default there.

Do you mind posting more code? It looks like it's not related to Mongorito.

**Comment by fmvilas** [comment]
Ok, found the issue. Sorry for that. I was not using ```co``` module. I'm new to generators and i'm wondering if it's really necessary to use ```co``` or wrap the code around another generator.

What i had before:

```js
const Mongorito = require('mongorito');
const Model = Mongorito.Model;

  // connect to localhost/iris
  yield Mongorito.connect('localhost/iris');

  // define model
  class Token extends Model {

  }

  // create and save new Post document
  let token = new Token({
    title: 'Node.js with --harmony rocks!',
    body: 'Long post body',
    author: {
      name: 'John Doe'
    }
  });

  yield token.save();
```

What i have now:

```js
const co = require('co');
const Mongorito = require('mongorito');
const Model = Mongorito.Model;

co(function*() {
  // connect to localhost/iris
  yield Mongorito.connect('localhost/iris');

  // define model
  class Token extends Model {

  }

  // create and save new Post document
  let token = new Token({
    title: 'Node.js with --harmony rocks!',
    body: 'Long post body',
    author: {
      name: 'John Doe'
    }
  });

  yield token.save();
});
```

That works wrapping inside another generator. I was trying to use methods like connect and save without yield but doesn't work.

Thanks!

**Comment by vdemedes** [comment]
No probs.
