### ISSUE TITLE
ACID support

### ISSUE THREAD

**Issue by avivcarmis** [vdemedes/mongorito#71]
Thought about adding ACID support by implementing an optional Transaction concept into Mongorito.

E.g. some like

```
Mongorito.connect('localhost/blog');
Mongorito.transaction.begin();
class Post extends Model {}
var post = new Post({ ... });
post.save(); // at the meantime all queries to DB will be buffered to enable validating all business logic is completed as expected.
var success = true;
try {
  // some business logic
}
catch (e) {
  // our business logic failed, roll back all transaction changes
  success = false;
}
if (success) {
  Mongorito.transaction.commit(); // will update all buffered changes into database
}
else {
  Mongorito.transaction.rollback(); // will remove all buffered changes in the current transaction
}
```

More info on Transaction (with Hibernate OPM) concept can be found here: https://docs.jboss.org/hibernate/orm/3.3/reference/en/html/transactions.html

I can supply a more concrete example to make this clearer.
Additionally, I'd be happy to contribute to such a feature if it would be found suited.

**Comment by vdemedes** [comment]
MongoDB does not have transactions, so I don't really want this to be in the core. If it would be a plugin/addon - no problems. I want to keep Mongorito as light as possible.
