### ISSUE TITLE
Support for Projection

### ISSUE THREAD

**Issue by b22n** [vdemedes/mongorito#74]

**Comment by vdemedes** [comment]
Would be great if you provided more information for that issue.

**Comment by b22n** [comment]
Query Projection is essential functionality of db query
and mongodb also support this

https://docs.mongodb.org/manual/tutorial/project-fields-from-query-results/

**Comment by vdemedes** [comment]
If I got this correctly, Mongorito supports that:

```js
yield Post.include('title').find();
yield Post.exclude('author').find();
```

**Comment by b22n** [comment]
Ok, Thanks
