### ISSUE TITLE
Index options

### ISSUE THREAD

**Issue by mccraveiro** [vdemedes/mongorito#9]
Cannot pass unique option to collection.index(); 

https://github.com/Automattic/monk#indexes

**Comment by nicholaswyoung** [comment]
I didn't see a unique option in the docs, so I would love to see any information you can provide, @vdemedes.

**Comment by vdemedes** [comment]
Will fix during coming days.

**Comment by nicholaswyoung** [comment]
@vdemedes Cool. In the meantime, is there anything wrong with doing something like:

```javascript
* validate (next) {
  var duplicate = this.findOne({ title: this.title });
  if (duplicate) { throw new Error('Duplicate record!'); }
  yield next;
}
```

**Comment by vdemedes** [comment]
@nicholaswyoung I would do something like this:

```javascript
* validate (next) {
  let isDuplicate = yield Post.findOne({ title: this.get('title') });
  
  if (isDuplicate) {
    throw new Error('Duplicate record!');
  }
 
  yield next;
}
```

`this.findOne` and `this.title` wouldn't work.

As for idea of fetching other records in hooks, it's absolutely fine. Think of it as Koa/Express middleware.

**Comment by nicholaswyoung** [comment]
@vdemedes Perfect! That will do exactly what I need. Thanks!

**Comment by vdemedes** [comment]
Here's how to set unique index:

```javascript
yield Post.index('title', { unique: true });
```
