### ISSUE TITLE
Mongorito.connect creates a db with 'undefined' name

### ISSUE THREAD

**Issue by AleffHenrique** [vdemedes/mongorito#91]
I am using Node v5.3.0, MongoDB v2.6.6 and Mongorito v1.4.6 on Windows 10 and when I executed this piece of code: 

```JavaScript
Mongorito.connect('localhost/mydb');
```

I was expecting a db named "mydb" but when I run Mongo's ```show dbs``` command a db named 'undefined' was created instead.

The same happen when I tried to run: 

```JavaScript
Mongorito.connect('mongodb://localhost:27017/mydb');
```

Is it a bug or I am doing something wrong?

**Comment by vdemedes** [comment]
I used the exact same specs (but MongoDB 3.x) and couldn't reproduce this.

**Comment by AleffHenrique** [comment]
I also tried use Mongoose and the same happen, I have no idea what are going on but It is definetely not a mongorito's bug ^^
