### ISSUE TITLE
Optional Schema definition

### ISSUE THREAD

**Issue by AleffHenrique** [vdemedes/mongorito#92]
> There is no need to define schema or even fields that belong to this model. One of the main features of MongoDB is that it’s schema-less and Mongorito does not want to take that feature away from you.

I think it should also support schema definition as well if someone desire to use it [IMHO].

**Comment by vdemedes** [comment]
I don't think I want this in the core, as Mongorito intended to be different from other libraries. All of them (which I know) require a schema and I don't really like it. One of the greatest features of MongoDB is schema-free documents, so I don't understand why some libraries would block that feature.

I see schema definition (even optional) in Mongorito only as a plugin, but not as a core feature.

**Comment by AleffHenrique** [comment]
@vdemedes What I was trying to say is also support schema definition for developers feel free to use what makes sense in your projects.

**Comment by devdebonair** [comment]
Would love to see a plugin for defining schemas.

**Comment by xouabita** [comment]
@devdebonair: I did a little plugin for that purpose: [mongorito-tcomb](https://github.com/xouabita/mongorito-tcomb)

**Comment by vdemedes** [comment]
@AleffHenrique "Also support schema definition" equals to having it in the core, which I really don't want to do. If someone desperately wants schema, one would better just validate incoming data (which is necessary anyway) and write docs for the models :)

**Comment by devdebonair** [comment]
@vdemedes I agree with you. A plugin can be implemented. The core should be as bare bones as possible. I ended up using Joi setting an instance variable called schema to be a Joi object in my model. Then I just run validation with the hooks you provided.

Example
----------------

```javascript
import { Model } from 'mongorito';
import Joi from 'joi'

export default class User extends Model {
    configure(){
        this.before('create', 'validate');

        this.schema = Joi.object().keys({
            email: Joi.string().email().trim().required(),
            password: Joi.string().min(5).max(18).trim().required(),
            name: {
                first: Joi.string().lowercase().trim().required(),
                last: Joi.string().lowercase().trim().required()
            },
            profile_picture: {
                url: Joi.string().uri().required(),
                width: Joi.number().integer().positive().required(),
                height: Joi.number().integer().positive().required()
            }
        });
    }

    *validate(next){
        const attributes = omit(this.attributes, ['created_at','updated_at']);
        const result = this.schema.validate(attributes);
        if(isEmpty(result.error)){
            return yield next;
        }
        throw new Error(result.error.details[0].message);
    }
}
```
