### ISSUE TITLE
Connection errors when application starts

### ISSUE THREAD

**Issue by burgalon** [vdemedes/mongorito#93]
I'm using Mongorito with MongoLab (addon).
50% of the time when the app comes out of sleep mode, it gets an exception of bad connection

```
2016-01-11T14:45:17.549001+00:00 app[web.1]: Unhandled Rejection at: Promise  Promise {
2016-01-11T14:45:17.549009+00:00 app[web.1]:   <rejected> [TypeError: Cannot read property 's' of undefined] }  reason:  [TypeError: Cannot read property 's' of undefined]
2016-01-11T14:45:17.552551+00:00 app[web.1]: TypeError: Cannot read property 's' of undefined
2016-01-11T14:45:17.552554+00:00 app[web.1]:     at Function._collection (/app/node_modules/mongorito/lib/mongorito.js:103:15)
2016-01-11T14:45:17.552556+00:00 app[web.1]:     at Function.Model._collection (/app/node_modules/mongorito/lib/mongorito.js:663:19)
```

My connection.js looks like this:
```
'use strict';
let Mongorito = require('mongorito');

class Connection {
  constructor () {
  }

  connect() {
    return Mongorito.connect(process.env.MONGOLAB_URI || 'localhost/example');
  }
}

module.exports = Connection
```

And app.js:
```
process.on('unhandledRejection', function(reason, p) {
  console.log("Unhandled Rejection at: Promise ", p, " reason: ", reason);
  console.log(reason.stack)
  process.exit(1);
});

let Connection = require('./connection')
let connection = new Connection
connection.connect()
```

Any idea why this might happen?

**Comment by vdemedes** [comment]
I think it's related to the fact, that Mongorito does not have command queue at the moment. In other words, this will crash:

```js
mongorito.connect();
Post.find();
```

Because Mongorito is not connected to MongoDB at the time when `Post.find()` is fired.

Try binding to a port after Mongorito connects to MongoDB. Here's an example:

```js
var app = express();

mongorito.connect().then(function () {
  app.listen(process.env.PORT);
});
```

**Comment by burgalon** [comment]
testing

**Comment by burgalon** [comment]
now the app is crashing for some reason... can't find any traces in the logs... localhost works fine, and also after the deployment it seemed to work... only when coming back from sleep, it creates some problem

**Comment by vdemedes** [comment]
Can't help you out without errors/stack traces, unfortunately.

**Comment by vdemedes** [comment]
Try catching exceptions and rejections and logging everything you can. Also, highly recommend using something like BugSnag or Rollbar.

**Comment by burgalon** [comment]
I think now it's crashing because it never gets to the PORT binding which Heroku waits for.
I am listening on unhandled exception (and able to see it locally if setting a bad connection URI), but not seeing it on Heroku

```
'use strict'

let express = require('express')
let app = express()

let bodyParser = require('body-parser')
var morgan = require('morgan')
const IS_PRODUCTION = !!process.env.MONGOLAB_URI

 Mongo logging
let Logger = require('mongodb').Logger
Logger.setLevel('debug')
Logger.filter('class', ['Cursor'])
Logger.setCurrentLogger(function(msg, context) {
  console.log(msg, context);
})

process.on('unhandledRejection', function(reason, p) {
  console.log("Unhandled Rejection at: Promise ", p, " reason: ", reason);
  console.log(reason.stack)
  process.exit(1);
});


app.use(bodyParser.urlencoded({ extended: true }))
app.use(bodyParser.json())
!IS_PRODUCTION && app.use(morgan('dev'))

app.use(function(err, req, res, next) {
  console.error(err.stack);
  res.status(500).send('Something broke!');
});

let ItemService = require('./ItemService')
new ItemService(app)


let Connection = require('./connection')
let connection = new Connection
connection.connect()
  .then(() => {
    app.listen(process.env.PORT || 3000)
  })

```

**Comment by vdemedes** [comment]
Try this:

```js
connection.connect()
  .then(() => {
    app.listen(process.env.PORT || 3000)
  })
  .catch(err => {
    console.log(err.stack);
  });
```

**Comment by burgalon** [comment]
seems like it's working now... not sure what made it crash before :)
maybe it's worth adding to the docs/example that you have to wait for the connection in order to start listening for HTTP requests
```
let Connection = require('./connection')
let connection = new Connection
connection.connect()
  .then(() => {
    app.listen(process.env.PORT || 3000)
  })
```

**Comment by vdemedes** [comment]
I was planning to actually solve that issue soon, because it really sucks to wait for connection.

**Comment by vdemedes** [comment]
Fixed in master, no code changes required.

**Comment by dcsan** [comment]
does this mean the connection can be written just as synchronous code? ie somehow you buffer any requests until its ready?

**Comment by vdemedes** [comment]
Yep, you no longer need to wait for connection to establish, just write code as you'd expect ;)
