### ISSUE TITLE
story.save(...).then is not a function

### ISSUE THREAD

**Issue by dcsan** [vdemedes/mongorito#97]
I tried a simple test based closely on your sample code but it seems to fail immediately.

```js

var Story = Model.extend({
    collection: 'story'
});

let story = new Story({
    cname: 'picnic',
    code: 'some code goes here'
});

    story.save().then( () => {
        console.log('story saved');
    });

```

```
node test/mongorito.js
stories.init
/Users/dc/dev/rnd/mongo-driver-comparison/test/mongorito.js:38
    story.save().then( () => {
                 ^

TypeError: story.save(...).then is not a function
    at test2 (/Users/dc/dev/rnd/mongo-driver-comparison/test/mongorito.js:38:18)
    at Object.<anonymous> (/Users/dc/dev/rnd/mongo-driver-comparison/test/mongorito.js:44:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:140:18)
    at node.js:1001:3
```

code is in a separate repo here:
https://github.com/dcsan/mongo-driver-comparison/blob/master/test/mongorito.js

**Comment by dcsan** [comment]
➜  mongo-driver-comparison git:(master) npm -v
3.6.0
➜  mongo-driver-comparison git:(master) node -v
v5.6.0

**Comment by edravis** [comment]
+1 
I straightforward copied the example from the README.md

**Comment by xouabita** [comment]
I think it is because the example in the README concern the next version of Mongorito but not the one we get with `npm`: https://www.npmjs.com/package/mongorito#usage

**Comment by vdemedes** [comment]
@xouabita is right, the readme is for latest version, which is not released yet.

For now, you can `npm install vdemedes/mongorito` and it will work as expected ;)

New version will be out soon!
