### ISSUE TITLE
clarify benefits vs native mongo driver?

### ISSUE THREAD

**Issue by dcsan** [vdemedes/mongorito#98]
I'm trying to evaluate what benefits this provides over the 10gen 2.1 mongoDB driver itself.
that provides promises + various ES6 sugar now:
http://mongodb.github.io/node-mongodb-native/2.1/reference/ecmascript6/

could you let me know what the motivations for the project are? 
for example, perhaps the buffering of commands after a connection is open?
other significant API differences? thanks!

if you could compare with [Robe](http://hiddentao.github.io/robe/) or other ES6 drivers too that would be great. For example Robe depends on an outdated (1.4) version of the mongodriver...

**Comment by vdemedes** [comment]
The benefit is convenience. Native mongodb driver is perfect, depending on your needs. But ever after trying out ActiveRecord from Rails, I find using models (ORM) to be way more convenient and flexible. It's all up to you.

**Comment by vdemedes** [comment]
I can't compare Mongorito to Robe, because I haven't used it, so my biased opinion wouldn't give much useful info :)
